### ISSUE TITLE
Hey Pradyumna. I want your mail, I want to discuss something related to RainNet

### ISSUE THREAD

**Issue by syedhamidali** [PradyumnaGupta/neat_implementation_in_java#1]
Hey Pradyumna. I want your mail, I want to discuss something related to RainNet. I am working on a paper, and want to apply ML on it. If you have time we can set up a meeting, you can be a co-author in my paper.

**Comment by PradyumnaGupta** [comment]
Hi Syed, 
My email address is : pradyumna.gupta22@gmail.com
